export const moduleApiMap = {
  "user-management": "users",
  "role-management": "roles",
  "workgroup-staff-management": "workgroups",
  "order-desk": "orders",
  "customer-order-search": "orders",
  "exception-monitoring": "exceptions",
  "task-desk": "tasks",
  "service-instance": "services",
  "service-assurance": "assurances",
  "sla-monitoring": "slas",
  "trouble-ticket": "tickets",
  "modify-mac": "macRecords",
  "migration-desk": "migrations",
  "resource-order": "resourceOrders",
  "resource-task": "resourceTasks",
  "my-task": "wfmTasks",
  "list-monitor": "wfmTasks",
  "team-management": "teams",
  "bsnl-request-monitoring": "bsnlRequests",
  "bsnl-history-monitoring": "bsnlRequests",
  "mpls-bulk-monitoring": "mplsBatches",
  "bsnl-franchisee-pending-docket": "dockets",
  "active-alarms": "alarms",
  "incident-lifecycle": "incidents",
  "audit-trail": "auditLogs",
};
