/* ============================================================
   ZSMART OSS — PORTALS CONFIG  (single source of truth)
   ------------------------------------------------------------
   Drives: the portal drawer, each portal home (card grid),
   the per-portal sidebar, and the router. Add a module = add
   one entry below. List pages render generically via
   ModuleListPage using `columns` + `searchFields` + mock data.
   Pages flagged `view: "special"` are hand-built components.
   ============================================================ */

import * as mocks from "../data/mock/index.js";

// Re-export the ordered portal list for the drawer.
export const PORTAL_ORDER = [
  "itc-admin",
  "iom",
  "isap",
  "im",
  "resource",
  "wfm",
  "ofm",
  "fault",
  "analytics",
];

export const portals = [
  {
    id: "itc-admin",
    name: "IT Center Administrator Portal",
    icon: "🛡️",
    accent: "#4d96ff",
    blurb: "Identity, roles and workforce administration",
    modules: [
      {
        id: "user-management",
        title: "User Management",
        icon: "👤",
        group: "User Management",
        description: "Provision and manage system users",
        view: "list",
        columns: mocks.userColumns,
        searchFields: mocks.userSearchFields,
        rows: mocks.users,
        actions: ["Create User", "Reset Password", "Disable", "Export"],
      },
      {
        id: "role-management",
        title: "Role Management",
        icon: "🧾",
        group: "User Management",
        description: "Define roles and permission profiles",
        view: "list",
        columns: mocks.roleColumns,
        searchFields: mocks.roleSearchFields,
        rows: mocks.roles,
        actions: ["Create Role", "Assign Permissions", "Export"],
      },
      {
        id: "workgroup-staff-management",
        title: "Workgroup & Staff Management",
        icon: "👥",
        group: "User Management",
        description: "Organize workgroups and assign staff",
        view: "list",
        columns: mocks.workgroupColumns,
        searchFields: mocks.workgroupSearchFields,
        rows: mocks.workgroups,
        actions: ["Create Workgroup", "Assign Staff", "Export"],
      },
    ],
  },

  {
    id: "iom",
    name: "IOM Management Portal",
    icon: "📋",
    accent: "#2f6df6",
    blurb: "Order lifecycle, provisioning & exception handling",
    modules: [
      {
        id: "order-desk",
        title: "Order Desk",
        icon: "📦",
        description: "Service order lifecycle & tracking",
        view: "list",
        columns: mocks.orderColumns,
        searchFields: mocks.orderSearchFields,
        rows: mocks.orders,
        actions: ["Check-in", "Re-dispatch", "Redo", "Export"],
      },
      {
        id: "exception-monitoring",
        title: "Exception Monitoring",
        icon: "⚠️",
        description: "Orders in exception state & SLA breaches",
        view: "list",
        columns: mocks.exceptionColumns,
        searchFields: mocks.exceptionSearchFields,
        rows: mocks.exceptions,
        actions: ["Escalate", "Auto-resolve", "Export"],
      },
      {
        id: "task-desk",
        title: "Task Desk",
        icon: "✓",
        description: "Provisioning tasks assigned to workgroups",
        view: "list",
        columns: mocks.taskColumns,
        searchFields: mocks.taskSearchFields,
        rows: mocks.tasks,
        actions: ["Assign", "Reassign", "Complete", "Export"],
      },
      {
        id: "customer-order-search",
        title: "Customer Order Search",
        icon: "🔍",
        description: "Search orders across all states & history",
        view: "list",
        columns: mocks.orderColumns,
        searchFields: mocks.orderSearchFields,
        rows: mocks.orders,
        actions: ["Search", "Export"],
      },
      {
        id: "service-instance",
        title: "Service Instance",
        icon: "⚙️",
        description: "Active service instances & status",
        view: "list",
        columns: mocks.serviceColumns,
        searchFields: mocks.serviceSearchFields,
        rows: mocks.services,
        actions: ["View Details", "Suspend", "Export"],
      },
    ],
  },

  {
    id: "isap",
    name: "ISAP Portal",
    icon: "📶",
    accent: "#9d84b7",
    blurb: "Integrated service assurance & performance",
    modules: [
      {
        id: "service-assurance",
        title: "Service Assurance",
        icon: "🛰️",
        description: "End-to-end service health monitoring",
        view: "list",
        columns: mocks.assuranceColumns,
        searchFields: mocks.assuranceSearchFields,
        rows: mocks.assurance,
        actions: ["Open Ticket", "Acknowledge", "Export"],
      },
      {
        id: "sla-monitoring",
        title: "SLA Monitoring",
        icon: "⏱️",
        description: "SLA compliance & breach tracking",
        view: "list",
        columns: mocks.slaColumns,
        searchFields: mocks.slaSearchFields,
        rows: mocks.sla,
        actions: ["Escalate", "Export"],
      },
      {
        id: "trouble-ticket",
        title: "Trouble Ticket",
        icon: "🎫",
        description: "Customer trouble ticket lifecycle",
        view: "list",
        columns: mocks.ticketColumns,
        searchFields: mocks.ticketSearchFields,
        rows: mocks.tickets,
        actions: ["Create Ticket", "Assign", "Close", "Export"],
      },
      {
        id: "performance-monitoring",
        title: "Performance Monitoring",
        icon: "📈",
        description: "KPIs & network performance metrics",
        view: "special",
        component: "PerformanceMonitoring",
      },
    ],
  },

  {
    id: "im",
    name: "IM Portal",
    icon: "🗂️",
    accent: "#6bcb77",
    blurb: "Network resource inventory & migration",
    modules: [
      {
        id: "inventory-management",
        title: "Inventory Management",
        icon: "📦",
        description: "Hierarchical network resource catalog",
        view: "special",
        component: "InventoryManagement",
      },
      {
        id: "modify-mac",
        title: "Modify MAC",
        icon: "🛠️",
        description: "Modify MAC addresses on resources",
        view: "list",
        columns: mocks.macColumns,
        searchFields: mocks.macSearchFields,
        rows: mocks.macRecords,
        actions: ["Modify", "Export"],
      },
      {
        id: "migration-monitor",
        title: "Migration Monitor",
        icon: "📈",
        description: "Live migration progress monitoring",
        view: "special",
        component: "MigrationMonitor",
      },
      {
        id: "migration-desk",
        title: "Migration Desk",
        icon: "🖥️",
        description: "Plan & execute network migrations",
        view: "list",
        columns: mocks.migrationColumns,
        searchFields: mocks.migrationSearchFields,
        rows: mocks.migrations,
        actions: ["Start Migration", "Rollback", "Export"],
      },
    ],
  },

  {
    id: "resource",
    name: "Resource Assign",
    icon: "🎯",
    accent: "#f0a500",
    blurb: "Resource order & task assignment",
    modules: [
      {
        id: "resource-order",
        title: "Resource Order",
        icon: "📄",
        description: "Resource provisioning orders",
        view: "list",
        columns: mocks.resourceOrderColumns,
        searchFields: mocks.resourceOrderSearchFields,
        rows: mocks.resourceOrders,
        actions: ["Assign", "Release", "Export"],
      },
      {
        id: "resource-task",
        title: "Resource Task",
        icon: "✓",
        description: "Resource assignment tasks",
        view: "list",
        columns: mocks.resourceTaskColumns,
        searchFields: mocks.resourceTaskSearchFields,
        rows: mocks.resourceTasks,
        actions: ["Complete", "Reassign", "Export"],
      },
    ],
  },

  {
    id: "wfm",
    name: "WFM Admin Portal",
    icon: "👷",
    accent: "#ff6b6b",
    blurb: "Workforce / field task management",
    modules: [
      {
        id: "my-task",
        title: "My Task",
        icon: "✓",
        description: "Tasks assigned to me",
        view: "list",
        columns: mocks.wfmTaskColumns,
        searchFields: mocks.wfmTaskSearchFields,
        rows: mocks.wfmTasks,
        actions: ["Accept", "Complete", "Export"],
      },
      {
        id: "list-monitor",
        title: "List Monitor",
        icon: "📋",
        description: "Monitor all team task queues",
        view: "list",
        columns: mocks.wfmTaskColumns,
        searchFields: mocks.wfmTaskSearchFields,
        rows: mocks.wfmTasks,
        actions: ["Reassign", "Export"],
      },
      {
        id: "team-management",
        title: "Team Management",
        icon: "👥",
        description: "Field teams & crew roster",
        view: "list",
        columns: mocks.teamColumns,
        searchFields: mocks.teamSearchFields,
        rows: mocks.teams,
        actions: ["Create Team", "Assign Lead", "Export"],
      },
    ],
  },

  {
    id: "ofm",
    name: "OFM Portal",
    icon: "🚚",
    accent: "#357abd",
    blurb: "Operations / field monitoring & BSNL workflows",
    modules: [
      {
        id: "bsnl-request-monitoring",
        title: "BSNL Request Monitoring",
        icon: "📊",
        description: "Live BSNL service requests",
        view: "list",
        columns: mocks.bsnlColumns,
        searchFields: mocks.bsnlSearchFields,
        rows: mocks.bsnlRequests,
        actions: ["Process", "Export"],
      },
      {
        id: "bsnl-history-monitoring",
        title: "BSNL History Monitoring",
        icon: "🕘",
        description: "Historical BSNL request archive",
        view: "list",
        columns: mocks.bsnlColumns,
        searchFields: mocks.bsnlSearchFields,
        rows: mocks.bsnlHistory,
        actions: ["Export"],
      },
      {
        id: "mpls-bulk-monitoring",
        title: "MPLS Bulk Monitoring",
        icon: "📡",
        description: "MPLS bulk provisioning batches",
        view: "list",
        columns: mocks.mplsColumns,
        searchFields: mocks.mplsSearchFields,
        rows: mocks.mplsBatches,
        actions: ["Retry Failed", "Export"],
      },
      {
        id: "bbnw-report",
        title: "BBNW Report",
        icon: "📈",
        description: "Backhaul network weekly report",
        view: "special",
        component: "BbnwReport",
      },
      {
        id: "bsnl-franchisee-pending-docket",
        title: "BSNL/Franchisee Pending Docket",
        icon: "📁",
        description: "Pending docket items for BSNL & franchisees",
        view: "list",
        columns: mocks.docketColumns,
        searchFields: mocks.docketSearchFields,
        rows: mocks.dockets,
        actions: ["Follow-up", "Close", "Export"],
      },
      {
        id: "migration-monitor",
        title: "Migration Monitor",
        icon: "📈",
        description: "Live migration progress monitoring",
        view: "special",
        component: "MigrationMonitor",
      },
    ],
  },

  {
    id: "fault",
    name: "Fault Management Portal",
    icon: "🚨",
    accent: "#ff4d4d",
    blurb: "Alarm monitoring & incident lifecycle",
    modules: [
      {
        id: "alarm-dashboard",
        title: "Alarm Dashboard",
        icon: "🚨",
        description: "Real-time alarm overview & KPIs",
        view: "special",
        component: "AlarmDashboard",
      },
      {
        id: "active-alarms",
        title: "Active Alarms",
        icon: "🔔",
        description: "Live active network alarms",
        view: "list",
        columns: mocks.alarmColumns,
        searchFields: mocks.alarmSearchFields,
        rows: mocks.alarms,
        actions: ["Acknowledge", "Suppress", "Create Incident", "Export"],
      },
      {
        id: "incident-lifecycle",
        title: "Incident Lifecycle",
        icon: "🔧",
        description: "Incident creation through resolution",
        view: "list",
        columns: mocks.incidentColumns,
        searchFields: mocks.incidentSearchFields,
        rows: mocks.incidents,
        actions: ["Escalate", "Resolve", "Export"],
      },
      {
        id: "alarm-topology",
        title: "Alarm Topology",
        icon: "🌐",
        description: "Network topology alarm view",
        view: "special",
        component: "AlarmTopology",
      },
    ],
  },

  {
    id: "analytics",
    name: "Analytics & Reporting",
    icon: "📊",
    accent: "#5f27cd",
    blurb: "KPI dashboards & operational audit",
    modules: [
      {
        id: "kpi-dashboard",
        title: "KPI / SLA Dashboard",
        icon: "📊",
        description: "Cross-portal KPI & SLA analytics",
        view: "special",
        component: "KpiDashboard",
      },
      {
        id: "audit-trail",
        title: "Audit Trail",
        icon: "🧾",
        description: "Immutable audit log of all actions",
        view: "list",
        columns: mocks.auditColumns,
        searchFields: mocks.auditSearchFields,
        rows: mocks.audit,
        actions: ["Export"],
      },
    ],
  },
];

// ---- Lookup helpers used across the app ----
export const getPortal = (portalId) => portals.find((p) => p.id === portalId);

export const getModule = (portalId, moduleId) => {
  const p = getPortal(portalId);
  return p?.modules.find((m) => m.id === moduleId);
};

// All list-type modules flattened, for quick iteration.
export const allListModules = () =>
  portals.flatMap((p) =>
    p.modules.filter((m) => m.view === "list").map((m) => ({ portal: p, module: m }))
  );
